-- 코드를 입력하세요
-- 도서정보: BOOK
-- 저자정보: AUTHOR
-- 각 도서의 날짜별 판매량 정보: BOOK_SALES

-- 2022.01 도서 판매 데이터를 기준으로
-- 저자별, 카테고리 별 매출액
-- 저자id, 저자명, 카테고리, 매출액 출력
-- 저자id 오름차순, 카테고리 내림

SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(BS.SALES * B.PRICE ) AS TOTAL_SALES
FROM BOOK B
JOIN AUTHOR A ON A.AUTHOR_ID=B.AUTHOR_ID
JOIN BOOK_SALES BS ON B.BOOK_ID=BS.BOOK_ID
WHERE BS.SALES_DATE LIKE '2022-01%'
GROUP BY A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY  A.AUTHOR_ID, B.CATEGORY DESC;