-- 코드를 입력하세요
-- 1. 서울에 위치한 식당 필터링
-- 2. 평균 점수 계산: 소수점 3번째에서 반올림, 내림차순 정렬
-- 3. 평균 점수 같다면: 즐거찾기 수 내림차순 정렬

SELECT 
    RI.REST_ID AS REST_ID,
    REST_NAME,
    FOOD_TYPE,
    FAVORITES,
    ADDRESS,
    ROUND(AVG(RR.REVIEW_SCORE),2) AS SCORE
FROM REST_INFO RI JOIN REST_REVIEW RR ON RI.REST_ID = RR.REST_ID
WHERE RI.ADDRESS LIKE '서울%'
GROUP BY RI.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS
ORDER BY SCORE DESC, FAVORITES DESC;