-- 코드를 입력하세요
-- '서울' 위치 식당 -> 식당 ID, 이름, 음식 종류, 즐겨찾기 수, 주소, 리뷰 평균 점수(총 점수/ 리뷰 개수)

SELECT I.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE 
FROM REST_INFO I
JOIN REST_REVIEW R
ON I.REST_ID = R.REST_ID
WHERE ADDRESS LIKE '서울%'
GROUP BY I.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS
ORDER BY SCORE DESC, FAVORITES DESC