-- 코드를 입력하세요
-- USER_INFO: 회원정보
-- ONLINE_SALE: 판매정보
-- 
-- 오름차순
-- 성별 없을 경우 결과에서 제외
SELECT
    YEAR(SALES_DATE) AS YEAR,
    MONTH(SALES_DATE) AS MONTH,
    GENDER,
    COUNT(DISTINCT O.USER_ID) AS USERS
FROM USER_INFO U
JOIN ONLINE_SALE O ON U.USER_ID=O.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY 1,2,3
ORDER BY 1,2,3;