-- 코드를 입력하세요
-- 평균 대여 기간이 7일 이상인 자동차 id, 평균 대여 기간
-- DATEDIFF 사용-> 오늘대여, 오늘반납도 1일로 침
SELECT CAR_ID, ROUND(AVG(DATEDIFF(END_DATE, START_DATE)+1),1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING AVERAGE_DURATION >=7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC;