-- 코드를 입력하세요
-- 2022년 10월 16일에 대여 중인 자동차인 경우 '대여중' 이라고 표시
-- 어떻게 2022년 10월 16일에 대여 중인걸 알지?
-- END - START?

WITH temp as
(SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE<= '20221016' AND END_DATE>= '20221016'
GROUP BY CAR_ID)

SELECT DISTINCT CAR_ID, 
CASE WHEN CAR_ID IN (SELECT * FROM temp)
THEN '대여중'
ELSE '대여 가능'
END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
ORDER BY CAR_ID DESC