-- 코드를 입력하세요
-- 입양 못간 동물 중, 가장 오래 보호소에 있었던 동물 3마리의 이름, 보호시작일

SELECT I.NAME, I.DATETIME
FROM ANIMAL_INS I
WHERE NOT EXISTS (
    SELECT *
    FROM ANIMAL_OUTS O
    WHERE I.ANIMAL_ID=O.ANIMAL_ID
)
ORDER BY I.DATETIME
LIMIT 3;