-- 코드를 입력하세요
-- 몇 시에 입양이 가장 활발하게 일어나는지
-- 0~23시 각 시간대별로 입양 몇건? -> DATETIME 에서 시간 추출하기
-- 시간대 순으로 정렬


WITH RECURSIVE HOURS AS (
    SELECT 0 AS HOUR UNION ALL SELECT HOUR + 1 
    FROM HOURS
    WHERE HOUR < 23
)

SELECT HOURS.HOUR AS HOUR, COUNT(ANIMAL_ID) AS 'COUNT' 
FROM ANIMAL_OUTS RIGHT JOIN HOURS
ON DATE_FORMAT(DATETIME,'%H') = HOURS.HOUR
GROUP BY HOUR
ORDER BY HOUR;