-- 코드를 입력하세요
-- 중고거래 게시판: USED_GOODS_BOARD
-- 중고거래 사용자: USED_GOODS_USER
-- 완료된 중고 거래의 총금액이 70만원 이상인 사람
-- 총거래금액 기준으로 오름차순 정렬

SELECT USER_ID, NICKNAME, SUM(PRICE) as TOTAL_SALES
FROM USED_GOODS_USER U
JOIN USED_GOODS_BOARD B
ON B.WRITER_ID=U.USER_ID 
WHERE STATUS = 'DONE'
GROUP BY USER_ID, NICKNAME -- SELECT 절에 나온 컬럼있어야 함
HAVING SUM(PRICE)>=700000
ORDER BY TOTAL_SALES;


