-- 코드를 입력하세요
-- 완료된 중고 거래의 총금액이 70만 원 이상인 사람
 

SELECT u.USER_ID, u.NICKNAME, SUM(b.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD b join USED_GOODS_USER u
on b.WRITER_ID = u.USER_ID
WHERE b.STATUS = 'DONE'
GROUP BY u.USER_ID
HAVING TOTAL_SALES >=700000
ORDER BY 3