-- 코드를 작성해주세요

-- 1. 사원별 평가등급 구하기 -> 성과금 계산
WITH GRADE_CAL AS
(
    SELECT EMP_NO, ROUND(AVG(SCORE),2) AS AVG_SCORE
    FROM HR_GRADE 
    GROUP BY EMP_NO
),
GRADE_AND_BOUNS AS
(
    SELECT
        C.EMP_NO,
    CASE
        WHEN C.AVG_SCORE >= 96 THEN 'S'
        WHEN C.AVG_SCORE >= 90 THEN 'A'
        WHEN C.AVG_SCORE >= 80 THEN 'B'
        ELSE 'C'
    END AS GRADE,
    CASE
        WHEN C.AVG_SCORE >= 96 THEN E.SAL*0.2
        WHEN C.AVG_SCORE >= 90 THEN E.SAL*0.15
        WHEN C.AVG_SCORE >= 80 THEN E.SAL*0.1
        ELSE 0
    END AS BONUS
    FROM GRADE_CAL C
    JOIN HR_EMPLOYEES E ON C.EMP_NO=E.EMP_NO
)
SELECT E.EMP_NO, E.EMP_NAME, G.GRADE, G.BONUS
FROM GRADE_AND_BOUNS G
JOIN HR_EMPLOYEES E ON G.EMP_NO=E.EMP_NO
ORDER BY E.EMP_NO;

