-- 코드를 입력하세요
-- MEMBER PROFILE: 고객 정보
-- REST_REVIEW: 식당 리뷰 정보
-- "리뷰를 가장 많이" 작성한 회원의 리뷰 조회
-- 회원 이름, 리뷰 텍스트, 리뷰 작성일 출력
-- 리뷰 작성일 기준 오름차순, 리뷰 텍스트 오름차순

SELECT
    MEMBER_NAME,
    REVIEW_TEXT,
    DATE_FORMAT(REVIEW_DATE, '%Y%-%m%-%d') AS REVIEW_DATE
FROM REST_REVIEW R
LEFT JOIN MEMBER_PROFILE M
ON 
   R.MEMBER_ID=M.MEMBER_ID
WHERE R.MEMBER_ID=(
    SELECT MEMBER_ID
    FROM (
        SELECT MEMBER_ID, COUNT(*) AS REVIEW_CNT
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ORDER BY REVIEW_CNT DESC
        LIMIT 1   
    ) AS TOP_REVIEWER
)
ORDER BY REVIEW_DATE, REVIEW_TEXT