-- 대여 시작일 기준으로 22년 8월~ 22년 10월까지 총 대여횟수가 5회 이상인 자동차
-- 해당 기간 동안의 월별 자동차 id 별 총 대여 횟수: RECORDS
-- 월 기준으로 오름차순 정렬, 자동차 id 기준 내림차순
-- 만약, 특정 월의 총 대여 횟수가 0인 경우 -> 결과에서 제외

SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
AND  CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(*)>=5
)
GROUP BY CAR_ID, MONTH(START_DATE)
ORDER BY MONTH, CAR_ID DESC
