-- 코드를 입력하세요
SELECT TITLE, b.BOARD_ID, REPLY_ID, r.WRITER_ID, r.CONTENTS,  DATE_FORMAT(r.CREATED_DATE, '%Y-%m-%d')
from USED_GOODS_BOARD b, USED_GOODS_REPLY r
where b.BOARD_ID = r.BOARD_ID and b.CREATED_DATE LIKE '2022-10%'
order by r.CREATED_DATE, TITLE